# Generated by Django 6.0.3 on 2026-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rush',
            field=models.BooleanField(default=False),
        ),
    ]
